# Generated by Django 2.1.5 on 2019-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('roadname', models.CharField(max_length=100)),
                ('noofspaces', models.IntegerField()),
                ('spacetype', models.CharField(max_length=100)),
                ('OBJECTID', models.IntegerField()),
                ('Point', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('long', models.DecimalField(decimal_places=9, max_digits=12)),
                ('last_update', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
    ]
