# Generated by Django 2.1.5 on 2019-03-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_auto_20190317_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carparkdata',
            name='spaces',
            field=models.IntegerField(null=True),
        ),
    ]
