# Generated by Django 2.1.5 on 2019-03-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0002_auto_20190315_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
