# Generated by Django 2.1.5 on 2019-03-16 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0003_bike_cm_last_insert_dttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 14, 30, 51, 537080, tzinfo=utc)),
        ),
    ]
