# Generated by Django 2.1.5 on 2019-03-16 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0005_auto_20190316_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 17, 12, 49, 284101, tzinfo=utc)),
        ),
    ]
