# Generated by Django 2.1.5 on 2019-03-16 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0006_auto_20190316_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 18, 13, 10, 737663, tzinfo=utc)),
        ),
    ]
