# Generated by Django 2.1.5 on 2019-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIHandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='last_update',
            field=models.DateTimeField(max_length=10),
        ),
    ]
