# Generated by Django 2.1.5 on 2019-02-11 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='position_lat',
        ),
        migrations.AddField(
            model_name='bike',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
