# Generated by Django 2.1.5 on 2019-02-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIHandling', '0003_auto_20190213_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='position_lnt',
            new_name='position_lng',
        ),
    ]
