# Generated by Django 2.1.5 on 2019-02-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIHandling', '0004_auto_20190213_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
