# Generated by Django 2.1.7 on 2019-02-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLuas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerTime', models.DateTimeField(verbose_name='ServerTime')),
                ('TrainCode', models.IntegerField()),
                ('StationFullName', models.CharField(max_length=100)),
                ('StationCode', models.CharField(max_length=100)),
                ('QueryTime', models.CharField(max_length=100)),
                ('Traindate', models.CharField(max_length=100)),
                ('Origin', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Origintime', models.CharField(max_length=100)),
                ('Destinationtime', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Lastlocation', models.CharField(max_length=100)),
                ('Duein', models.IntegerField()),
                ('Late', models.IntegerField()),
                ('Exparrival', models.CharField(max_length=100)),
                ('Expdepart', models.CharField(max_length=100)),
                ('Scharrival', models.CharField(max_length=100)),
                ('Schdepart', models.CharField(max_length=100)),
                ('Direction', models.CharField(max_length=100)),
                ('Traintype', models.CharField(max_length=100)),
                ('Locationtype', models.CharField(max_length=100)),
            ],
        ),
    ]
