# Generated by Django 2.1.5 on 2019-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busluas',
            name='Destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Destinationtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Direction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Duein',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Exparrival',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Expdepart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Lastlocation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Late',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Locationtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Origintime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='QueryTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Scharrival',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Schdepart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='ServerTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='StationCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='StationFullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='TrainCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Traindate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Traintype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
