# Generated by Django 2.1.5 on 2019-03-16 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0002_auto_20190224_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrishRailStationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationDesc', models.CharField(max_length=100, null=True)),
                ('StationAlias', models.CharField(max_length=100, null=True)),
                ('StationLatitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('StationLongitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('StationCode', models.CharField(max_length=6, null=True)),
                ('StationId', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Destinationtime',
            new_name='DestinationTime',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Exparrival',
            new_name='ExpArrival',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Expdepart',
            new_name='ExpDepart',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Duein',
            new_name='LastLocation',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Origintime',
            new_name='OriginTime',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Scharrival',
            new_name='SchArrival',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Schdepart',
            new_name='SchDepart',
        ),
        migrations.RenameField(
            model_name='busluas',
            old_name='Traindate',
            new_name='TrainDate',
        ),
        migrations.RemoveField(
            model_name='busluas',
            name='Lastlocation',
        ),
        migrations.RemoveField(
            model_name='busluas',
            name='Locationtype',
        ),
        migrations.RemoveField(
            model_name='busluas',
            name='Traintype',
        ),
        migrations.AddField(
            model_name='busluas',
            name='DueIn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='busluas',
            name='LocationType',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='busluas',
            name='TrainType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='busluas',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 17, 12, 49, 254658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Direction',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='Late',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='StationCode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='TrainCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
