# Generated by Django 2.1.5 on 2019-03-16 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0004_auto_20190316_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busluas',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 18, 13, 34, 197215, tzinfo=utc)),
        ),
    ]
