# Generated by Django 2.1.5 on 2019-03-16 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusLuas', '0005_auto_20190316_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='irishrailstationcode',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='busluas',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
