# Generated by Django 2.1.5 on 2019-03-16 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CityEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityevents',
            name='cm_last_insert_dttm',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
