# Generated by Django 2.1.5 on 2019-02-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityEvents', '0002_auto_20190218_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityevents',
            name='capacity',
        ),
    ]
