# Generated by Django 2.1.5 on 2019-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityEvents', '0003_remove_cityevents_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityevents',
            name='organization_id',
            field=models.BigIntegerField(),
        ),
    ]
