# Generated by Django 2.1.7 on 2019-02-20 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherPollution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
