# Generated by Django 2.1.7 on 2019-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherPollution', '0002_weather_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='Station',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='Temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='Weathercol',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='last_update',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rainfall',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='winddirection',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='windgust',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='windspeed',
            field=models.IntegerField(null=True),
        ),
    ]
