# Generated by Django 2.1.5 on 2019-03-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherPollution', '0004_auto_20190318_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='humidity',
            new_name='Humidity',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='pressure',
            new_name='Pressure',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='rainfall',
            new_name='Rainfall',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='Weathercol',
            new_name='Weather',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='winddirection',
            new_name='WindDirection',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='windgust',
            new_name='WindGust',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='windspeed',
            new_name='WindSpeed',
        ),
    ]
