# Generated by Django 2.1.7 on 2019-03-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherPollution', '0003_auto_20190314_1302'),
        ('WeatherPollution', '0006_auto_20190318_1436'),
    ]

    operations = [
    ]
